name: deployment
on:push

jobs:
  npm-build:
    name: npm-build job
    runs-on: ubuntu-latest

    steps:
    - name: checkout data
      uses: actions/checkout@v4

    - name: install dependences
      run：
        npm install
        npm run build
        
   - name: deployment
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: dev
        folder: build
